Add ticketing
bangkokrb/rubyconfth pull request #289
Opened 2023-05-10 04:59 UTC by olivierobert

## What happened

- Implement updated theme for this year's conference
- Rework the hero and add the link to the event page
 
## Insight

The illustration was generated by Midjourney with the prompt:

> illustration, hand-drawn marker style, minimalistic, simple, black and red lines only, white background, for website landing page, a Thai elephant illustration, an Asian city skyline illustration - Variations by @olivierobert (fast)

## Proof Of Work

|Small Screen|Large Screen|
|-|-|
|![image](https://github.com/bangkokrb/rubyconfth/assets/696529/88a0a7ca-bb25-44e2-a756-a351cc38b72a)|![image](https://github.com/bangkokrb/rubyconfth/assets/696529/50476546-dfb7-4599-a203-a8b760e86d67)|

2023-05-10 05:23 UTC, matthewmayer approved these changes

2023-05-10 07:47 UTC, matthewmayer requested changes
Can you add a netlify redirect from /tickets to the eventpop page for easy linking.

2023-05-12 04:53 UTC, olivierobert commented
@matthewmayer added in [e240d5f](https://github.com/bangkokrb/rubyconfth/pull/289/commits/e240d5f2d073bbf2163658a24f876843ad5daafe)

2023-05-12 06:59 UTC, matthewmayer approved these changes

2023-05-12 07:02 UTC, merged